// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MwabuLearn.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MwabuLearn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MwabuDbContext))]
    [Migration("20261006142354_CurriculumManagement")]
    partial class CurriculumManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Code")
                        .IsUnique();

                    b.HasIndex("TopicId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TopicId", "SortOrder");

                    b.ToTable("Competencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Competencies_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Code")
                        .IsUnique();

                    b.HasIndex("CountryCode", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Curricula", null, t =>
                        {
                            t.HasCheckConstraint("CK_Curricula_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId", "Code")
                        .IsUnique();

                    b.HasIndex("CurriculumId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CurriculumId", "SortOrder");

                    b.ToTable("CurriculumVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumVersions_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumVersionId", "Code")
                        .IsUnique();

                    b.HasIndex("CurriculumVersionId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CurriculumVersionId", "SortOrder");

                    b.ToTable("Grades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Grades_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId", "Code")
                        .IsUnique();

                    b.HasIndex("CompetencyId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CompetencyId", "SortOrder");

                    b.ToTable("LearningOutcomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningOutcomes_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "Code")
                        .IsUnique();

                    b.HasIndex("GradeId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("GradeId", "SortOrder");

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Code")
                        .IsUnique();

                    b.HasIndex("SubjectId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("SubjectId", "SortOrder");

                    b.ToTable("Terms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Terms_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Code")
                        .IsUnique();

                    b.HasIndex("TermId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TermId", "SortOrder");

                    b.ToTable("Topics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Topics_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Topic", "Topic")
                        .WithMany("Competencies")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("CurriculumVersions")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany("Grades")
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumVersion");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.LearningOutcome", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Competency", "Competency")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Subject", "Subject")
                        .WithMany("Terms")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Term", "Term")
                        .WithMany("Topics")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.Navigation("LearningOutcomes");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Curriculum", b =>
                {
                    b.Navigation("CurriculumVersions");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Competencies");
                });
#pragma warning restore 612, 618
        }
    }
}
