// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MwabuLearn.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MwabuLearn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MwabuDbContext))]
    [Migration("20261006150214_ContentManagement")]
    partial class ContentManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Code")
                        .IsUnique();

                    b.HasIndex("TopicId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TopicId", "SortOrder");

                    b.ToTable("Competencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Competencies_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Collections", null, t =>
                        {
                            t.HasCheckConstraint("CK_Collections_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPendingDeletion")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "SortOrder");

                    b.ToTable("ContentAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentAssets_AssetType", "\"AssetType\" IN ('Document', 'Audio', 'Video', 'Image', 'Animation', 'Package', 'Other')");

                            t.HasCheckConstraint("CK_ContentAssets_FileSize", "\"FileSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ContentAssets_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "SortOrder");

                    b.HasIndex("ContentItemId", "CollectionId")
                        .IsUnique();

                    b.ToTable("ContentCollections", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentCollections_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCurriculumMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LearningOutcomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("CurriculumVersionId");

                    b.HasIndex("GradeId");

                    b.HasIndex("LearningOutcomeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TermId");

                    b.HasIndex("TopicId");

                    b.HasIndex("ContentItemId", "CompetencyId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "CurriculumVersionId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "GradeId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "LearningOutcomeId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "SubjectId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "TermId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "TopicId")
                        .IsUnique();

                    b.ToTable("ContentCurriculumMappings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentCurriculumMappings_OneTarget", "CASE WHEN \"CurriculumVersionId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"GradeId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"SubjectId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"TermId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"TopicId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"CompetencyId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"LearningOutcomeId\" IS NOT NULL THEN 1 ELSE 0 END = 1");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SortOrder", "Id");

                    b.HasIndex("Status", "ContentType", "LanguageCode");

                    b.ToTable("ContentItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentItems_Duration", "\"EstimatedDurationMinutes\" IS NULL OR \"EstimatedDurationMinutes\" > 0");

                            t.HasCheckConstraint("CK_ContentItems_PublishedAt", "\"Status\" <> 'Published' OR \"PublishedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_ContentItems_SortOrder", "\"SortOrder\" >= 0");

                            t.HasCheckConstraint("CK_ContentItems_Status", "\"Status\" IN ('Draft', 'InReview', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ContentItemId", "TagId")
                        .IsUnique();

                    b.ToTable("ContentTags", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Code")
                        .IsUnique();

                    b.HasIndex("CountryCode", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Curricula", null, t =>
                        {
                            t.HasCheckConstraint("CK_Curricula_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId", "Code")
                        .IsUnique();

                    b.HasIndex("CurriculumId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CurriculumId", "SortOrder");

                    b.ToTable("CurriculumVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumVersions_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumVersionId", "Code")
                        .IsUnique();

                    b.HasIndex("CurriculumVersionId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CurriculumVersionId", "SortOrder");

                    b.ToTable("Grades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Grades_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId", "Code")
                        .IsUnique();

                    b.HasIndex("CompetencyId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CompetencyId", "SortOrder");

                    b.ToTable("LearningOutcomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningOutcomes_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "Code")
                        .IsUnique();

                    b.HasIndex("GradeId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("GradeId", "SortOrder");

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Code")
                        .IsUnique();

                    b.HasIndex("SubjectId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("SubjectId", "SortOrder");

                    b.ToTable("Terms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Terms_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Code")
                        .IsUnique();

                    b.HasIndex("TermId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TermId", "SortOrder");

                    b.ToTable("Topics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Topics_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Topic", "Topic")
                        .WithMany("Competencies")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentAsset", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Assets")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCollection", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Content.Collection", "Collection")
                        .WithMany("Contents")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Collections")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCurriculumMapping", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("CurriculumMappings")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany()
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.LearningOutcome", "LearningOutcome")
                        .WithMany()
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Competency");

                    b.Navigation("ContentItem");

                    b.Navigation("CurriculumVersion");

                    b.Navigation("Grade");

                    b.Navigation("LearningOutcome");

                    b.Navigation("Subject");

                    b.Navigation("Term");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentTag", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Tags")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.Content.Tag", "Tag")
                        .WithMany("Contents")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("CurriculumVersions")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany("Grades")
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumVersion");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.LearningOutcome", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Competency", "Competency")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Subject", "Subject")
                        .WithMany("Terms")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Term", "Term")
                        .WithMany("Topics")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.Navigation("LearningOutcomes");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Collection", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentItem", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Collections");

                    b.Navigation("CurriculumMappings");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Tag", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Curriculum", b =>
                {
                    b.Navigation("CurriculumVersions");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Competencies");
                });
#pragma warning restore 612, 618
        }
    }
}
