// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MwabuLearn.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MwabuLearn.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MwabuDbContext))]
    [Migration("20261006222800_RegisteredDevices")]
    partial class RegisteredDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAt");

                    b.HasIndex("EntityId", "OccurredAt");

                    b.HasIndex("EventType", "OccurredAt");

                    b.HasIndex("OccurredAt", "Id");

                    b.HasIndex("OrganisationId", "OccurredAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "Code")
                        .IsUnique();

                    b.HasIndex("TopicId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TopicId", "SortOrder");

                    b.ToTable("Competencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Competencies_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Collections", null, t =>
                        {
                            t.HasCheckConstraint("CK_Collections_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPendingDeletion")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "SortOrder");

                    b.ToTable("ContentAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentAssets_AssetType", "\"AssetType\" IN ('Document', 'Audio', 'Video', 'Image', 'Animation', 'Package', 'Other')");

                            t.HasCheckConstraint("CK_ContentAssets_FileSize", "\"FileSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ContentAssets_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "SortOrder");

                    b.HasIndex("ContentItemId", "CollectionId")
                        .IsUnique();

                    b.ToTable("ContentCollections", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentCollections_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCurriculumMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LearningOutcomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId");

                    b.HasIndex("CurriculumVersionId");

                    b.HasIndex("GradeId");

                    b.HasIndex("LearningOutcomeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TermId");

                    b.HasIndex("TopicId");

                    b.HasIndex("ContentItemId", "CompetencyId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "CurriculumVersionId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "GradeId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "LearningOutcomeId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "SubjectId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "TermId")
                        .IsUnique();

                    b.HasIndex("ContentItemId", "TopicId")
                        .IsUnique();

                    b.ToTable("ContentCurriculumMappings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentCurriculumMappings_OneTarget", "CASE WHEN \"CurriculumVersionId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"GradeId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"SubjectId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"TermId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"TopicId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"CompetencyId\" IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN \"LearningOutcomeId\" IS NOT NULL THEN 1 ELSE 0 END = 1");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SortOrder", "Id");

                    b.HasIndex("Status", "ContentType", "LanguageCode");

                    b.ToTable("ContentItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContentItems_Duration", "\"EstimatedDurationMinutes\" IS NULL OR \"EstimatedDurationMinutes\" > 0");

                            t.HasCheckConstraint("CK_ContentItems_PublishedAt", "\"Status\" <> 'Published' OR \"PublishedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_ContentItems_SortOrder", "\"SortOrder\" >= 0");

                            t.HasCheckConstraint("CK_ContentItems_Status", "\"Status\" IN ('Draft', 'InReview', 'Published', 'Archived')");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ContentItemId", "TagId")
                        .IsUnique();

                    b.ToTable("ContentTags", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Code")
                        .IsUnique();

                    b.HasIndex("CountryCode", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Curricula", null, t =>
                        {
                            t.HasCheckConstraint("CK_Curricula_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId", "Code")
                        .IsUnique();

                    b.HasIndex("CurriculumId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CurriculumId", "SortOrder");

                    b.ToTable("CurriculumVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumVersions_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ClientRegistrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CredentialExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialHash")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("OrganisationId", "ClientRegistrationId")
                        .IsUnique();

                    b.HasIndex("OrganisationId", "IsActive", "Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurriculumVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumVersionId", "Code")
                        .IsUnique();

                    b.HasIndex("CurriculumVersionId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CurriculumVersionId", "SortOrder");

                    b.ToTable("Grades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Grades_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AccessTokenVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ReplacedBySessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("RefreshSessions");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CompetencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyId", "Code")
                        .IsUnique();

                    b.HasIndex("CompetencyId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("CompetencyId", "SortOrder");

                    b.ToTable("LearningOutcomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningOutcomes_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Operations.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("LeaseId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("State", "NextAttemptAt", "LeaseUntil");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganisationType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("ParentOrganisationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentOrganisationId");

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("Organisations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Organisations_NotSelfParent", "\"ParentOrganisationId\" IS NULL OR \"ParentOrganisationId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "IsActive");

                    b.HasIndex("UserId", "OrganisationId")
                        .IsUnique();

                    b.ToTable("OrganisationMemberships", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationMembershipRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("OrganisationMembershipId", "RoleId")
                        .IsUnique();

                    b.ToTable("OrganisationMembershipRoles", (string)null);
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GrantsPlatformAuthority")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrganisationRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000001"),
                            Code = "PlatformAdmin",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = true,
                            Name = "Platform Administrator"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000002"),
                            Code = "OrganisationAdmin",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Organisation Administrator"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000003"),
                            Code = "ProjectManager",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000004"),
                            Code = "HeadTeacher",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Head Teacher"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000005"),
                            Code = "Teacher",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000006"),
                            Code = "Learner",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Learner"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000007"),
                            Code = "ParentGuardian",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Parent / Guardian"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000008"),
                            Code = "ContentManager",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Content Manager"
                        },
                        new
                        {
                            Id = new Guid("51000000-0000-0000-0000-000000000009"),
                            Code = "DataAnalyst",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantsPlatformAuthority = false,
                            Name = "Data Analyst"
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000001"),
                            Code = "curriculum.read",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "curriculum read"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000002"),
                            Code = "curriculum.manage",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "curriculum manage"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000003"),
                            Code = "content.read",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "content read"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000004"),
                            Code = "content.manage",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "content manage"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000005"),
                            Code = "content.publish",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "content publish"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000006"),
                            Code = "users.read",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "users read"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000007"),
                            Code = "users.manage",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "users manage"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000008"),
                            Code = "organisations.read",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "organisations read"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000009"),
                            Code = "organisations.manage",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "organisations manage"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000010"),
                            Code = "memberships.manage",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "memberships manage"
                        },
                        new
                        {
                            Id = new Guid("52000000-0000-0000-0000-000000000011"),
                            Code = "reports.read",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "reports read"
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000004"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000005"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000007"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000007"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000009"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000009"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000010"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000010"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0001-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000011"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000002"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000004"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000005"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000007"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000007"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000009"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000009"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000010"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000010"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0002-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000011"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0003-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0003-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0003-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0003-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0003-000000000010"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000010"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0003-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000011"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0004-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0004-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0004-000000000006"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0004-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0004-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000011"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0005-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0005-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0005-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0006-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0006-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0007-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0008-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0008-000000000003"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0008-000000000004"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000004"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0008-000000000005"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000005"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0009-000000000008"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000008"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("53000000-0000-0000-0009-000000000011"),
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = new Guid("52000000-0000-0000-0000-000000000011"),
                            RoleId = new Guid("51000000-0000-0000-0000-000000000009")
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "Code")
                        .IsUnique();

                    b.HasIndex("GradeId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("GradeId", "SortOrder");

                    b.ToTable("Subjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subjects_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Code")
                        .IsUnique();

                    b.HasIndex("SubjectId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("SubjectId", "SortOrder");

                    b.ToTable("Terms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Terms_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Code")
                        .IsUnique();

                    b.HasIndex("TermId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TermId", "SortOrder");

                    b.ToTable("Topics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Topics_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("MwabuLearn.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("AccessTokenVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("IsActive", "Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MwabuLearn.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MwabuLearn.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MwabuLearn.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Topic", "Topic")
                        .WithMany("Competencies")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentAsset", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Assets")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCollection", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Content.Collection", "Collection")
                        .WithMany("Contents")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Collections")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentCurriculumMapping", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Competency", "Competency")
                        .WithMany()
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("CurriculumMappings")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany()
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.LearningOutcome", "LearningOutcome")
                        .WithMany()
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Domain.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Competency");

                    b.Navigation("ContentItem");

                    b.Navigation("CurriculumVersion");

                    b.Navigation("Grade");

                    b.Navigation("LearningOutcome");

                    b.Navigation("Subject");

                    b.Navigation("Term");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentTag", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Content.ContentItem", "ContentItem")
                        .WithMany("Tags")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.Content.Tag", "Tag")
                        .WithMany("Contents")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Curriculum", "Curriculum")
                        .WithMany("CurriculumVersions")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Devices.Device", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.CurriculumVersion", "CurriculumVersion")
                        .WithMany("Grades")
                        .HasForeignKey("CurriculumVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumVersion");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Identity.RefreshSession", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Identity.RefreshSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MwabuLearn.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.LearningOutcome", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Competency", "Competency")
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("CompetencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competency");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.Organisation", "ParentOrganisation")
                        .WithMany()
                        .HasForeignKey("ParentOrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentOrganisation");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationMembership", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.Organisation", "Organisation")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationMembershipRole", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.OrganisationMembership", "Membership")
                        .WithMany("Roles")
                        .HasForeignKey("OrganisationMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.OrganisationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.RolePermission", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MwabuLearn.Domain.Entities.Organisations.OrganisationRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Subject", "Subject")
                        .WithMany("Terms")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.HasOne("MwabuLearn.Domain.Entities.Term", "Term")
                        .WithMany("Topics")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Competency", b =>
                {
                    b.Navigation("LearningOutcomes");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Collection", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.ContentItem", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Collections");

                    b.Navigation("CurriculumMappings");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Content.Tag", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Curriculum", b =>
                {
                    b.Navigation("CurriculumVersions");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.CurriculumVersion", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationMembership", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Organisations.OrganisationRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Terms");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Term", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("MwabuLearn.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Competencies");
                });
#pragma warning restore 612, 618
        }
    }
}
